Repository wrtnlabs/autoview, pull requests merged in 2025-03, with the labels that each got.

#99 Publish configuration
  .github/workflows/release.yml
  package.json
  packages/compiler/package.json
  packages/interface/package.json
  packages/rpc/package.json
  packages/ui/package.json
Labels: Feature

#115 Fix agent tsconfig problem
  packages/agent/package.json
  packages/agent/tsconfig.json
  packages/compiler/tsconfig.json
  pnpm-lock.yaml
Labels: Bug

#57 Implement the Code Generation Agent
  packages/agent/package.json
  packages/agent/scripts/new-agent.ts
  packages/agent/src/agents/AutoViewAgent.ts
  packages/agent/src/agents/MainAgent.ts
  packages/agent/src/agents/index.ts
  packages/agent/src/passes/code-generation/Agent.ts
  packages/agent/src/passes/code-generation/dto.ts
  packages/agent/src/passes/code-generation/index.ts
  packages/agent/src/passes/code-generation/prompt.ts
  packages/agent/src/passes/common.ts
  packages/agent/src/passes/index.ts
  packages/agent/src/passes/plan-generation-agent/Agent.ts
  packages/agent/src/passes/plan-generation-agent/dto.ts
  packages/agent/src/passes/plan-generation-agent/index.ts
  packages/agent/src/passes/plan-generation-agent/prompt.ts
  packages/agent/src/passes/v2v-transform-agent/dto.ts
  packages/agent/src/passes/v2v-transform-agent/prompt.ts
  packages/agent/src/structures/properties/IAutoViewAccordionProps.ts
  packages/agent/src/structures/properties/IAutoViewCarouselProps.ts
  packages/agent/src/structures/properties/IAutoViewComponentProps.ts
  packages/agent/src/structures/properties/IAutoViewComponentPropsBase.ts
  packages/agent/src/structures/properties/IAutoViewGridProps.ts
  packages/agent/src/structures/properties/IAutoViewListProps.ts
  packages/agent/src/structures/properties/IAutoViewMarkdownProps.ts
  packages/compiler/package.json
  packages/compiler/src/AutoViewCompiler.ts
  packages/compiler/src/compilers/RollupBundler.ts
  packages/compiler/src/compilers/TypeScriptCompiler.ts
  packages/compiler/src/programmers/AutoViewClassProgrammer.ts
  packages/compiler/src/programmers/AutoViewDtoProgrammer.ts
  packages/compiler/src/programmers/AutoViewProgrammer.ts
  packages/compiler/src/programmers/AutoViewRandomProgrammer.ts
  packages/compiler/src/programmers/AutoViewTransformerProgrammer.ts
  packages/compiler/src/programmers/IAutoViewProgrammerContext.ts
  packages/interface/src/services/IAutoViewCompilerProps.ts
  packages/interface/src/services/IAutoViewCompilerResult.ts
  pnpm-lock.yaml
  test/src/features/test_agent_code_generation_agent.ts
  test/src/features/test_agent_v2v_transform_agent.ts
  test/src/features/test_compiler_failure.ts
  test/src/features/test_compiler_json_schema.ts
  test/src/features/test_compiler_llm_parameters.ts
  test/src/features/test_compiler_llm_schema.ts
  test/src/features/test_compiler_service.ts
  test/src/features/test_compiler_service_transform.ts
  test/src/features/test_compiler_transform.ts
  test/src/features/test_main_agent.ts
Labels: Feature

#126 Builder of AutoViewIconName type
  packages/interface/.gitignore
  packages/interface/build/iconName.ts
  packages/interface/package.json
  packages/interface/src/components/IAutoViewIconProps.ts
  packages/interface/tsconfig.json
  pnpm-lock.yaml
  typos.toml
Labels: Documentation, Enhancement, Feature

#128 Website publishing
  .github/workflows/website.yml
  packages/compiler-bundle/build/rspack.js
  pnpm-lock.yaml
  website/.gitignore
  website/app/[[...mdxPath]]/page.jsx
  website/app/layout.jsx
  website/build/compiler.js
  website/content/_meta.ts
  website/content/docs/_meta.ts
  website/content/docs/index.mdx
  website/content/docs/setup.mdx
  website/content/index.mdx
  website/eslint.config.mjs
  website/mdx-components.jsx
  website/next-env.d.ts
  website/next-sitemap.config.js
  website/next.config.ts
  website/package.json
  website/postcss.config.mjs
  website/public/.nojekyll
  website/public/favicon/android-chrome-192x192.png
  website/public/favicon/android-chrome-512x512.png
  website/public/favicon/apple-touch-icon.png
  website/public/favicon/favicon-16x16.png
  website/public/favicon/favicon-32x32.png
  website/public/favicon/favicon.ico
  website/public/favicon/site.webmanifest
  website/public/logo.png
  website/public/og.jpg
  website/tsconfig.json
  website/tsconfig.tsbuildinfo
Labels: Documentation

#129 Support both NodeJS and Browser rollup
  packages/compiler/package.json
  packages/compiler/src/compilers/RollupBundler.ts
  pnpm-lock.yaml
Labels: Documentation, Enhancement, Feature

#130 Rollup function as parameter
  packages/compiler-bundle/package.json
  packages/compiler-bundle/src/index.ts
  packages/compiler/package.json
  packages/compiler/src/AutoViewCompiler.ts
  packages/compiler/src/AutoViewCompilerService.ts
  packages/compiler/src/compilers/RollupBundler.ts
  packages/compiler/src/index.ts
  packages/compiler/src/worker/index.ts
  pnpm-lock.yaml
Labels: Documentation, Enhancement, Feature

#131 README document of compiler
  packages/compiler/README.md
  packages/compiler/src/worker/index.ts
  website/package.json
Labels: Documentation, Enhancement, Feature

#134 Try it once more
  packages/compiler/src/AutoViewCompiler.ts
  packages/compiler/src/compilers/RollupBundler.ts
  packages/compiler/src/compilers/TypeScriptCompiler.ts
Labels: Enhancement

#140 Bump up dependencies for exact `$ref` tracking
  packages/agent/package.json
  packages/compiler-browser-test/package.json
  packages/compiler/package.json
  packages/interface/package.json
  pnpm-lock.yaml
  test/package.json
Labels: Bug, Enhancement

#142 Playground openFile configuration
  pnpm-lock.yaml
  typos.toml
  website/app/_pages/Landing.tsx
  website/package.json
Labels: Documentation
