Repository wrtnlabs/autoview, pull requests merged in 2025-02, with the labels that each got.

#21 Writing principles
  README.md
Labels: Documentation

#53 How to use section
  README.md
  assets/logo.pptx
Labels: Documentation

#54 1st completion of README document
  README.md
Labels: Documentation

#59 Re-write component selection and rendering pipeline
  package.json
  pnpm-lock.yaml
  src/core/Agent.ts
  src/core/LlmProxy.ts
  src/core/ParseLlmOutput.ts
  src/core/Prompt.ts
  src/core/index.ts
  src/passes/component-selection-agent/ComponentSelectionAgent.ts
  src/passes/component-selection-agent/prompt.ts
  src/passes/main-content-extraction-agent/MainContentExtractionAgent.ts
  src/passes/main-content-extraction-agent/prompt.ts
  src/passes/v2v-transform-agent/V2vTransformAgent.ts
  src/passes/v2v-transform-agent/prompt.ts
  test/passes/ComponentSelectionAgent.test.ts
  test/passes/MainContentExtractionAgent.test.ts
  test/passes/V2vTransformAgent.test.ts
Labels: Enhancement

#67 Nested components
  src/passes/component-selection-agent/ComponentSelectionAgent.ts
  src/passes/component-selection-agent/prompt.ts
  src/passes/main-content-extraction-agent/MainContentExtractionAgent.ts
  src/passes/main-content-extraction-agent/dto.ts
  src/passes/v2v-transform-agent/V2vTransformAgent.ts
  src/passes/v2v-transform-agent/dto.ts
  src/passes/v2v-transform-agent/prompt.ts
  test/passes/ComponentSelectionAgent.test.ts
  test/passes/V2vTransformAgent.test.ts
Labels: Enhancement

#82 Data display: Popover, Stats, Table, Tag, Tooltip
  packages/interface/docs/data-display/en/badge.md
  packages/interface/docs/data-display/en/chip.md
  packages/interface/docs/data-display/en/divider.md
  packages/interface/docs/data-display/en/image-avatar.md
  packages/interface/docs/data-display/en/letter-avatar.md
  packages/interface/docs/data-display/en/popover.md
  packages/interface/docs/data-display/en/stats.md
  packages/interface/docs/data-display/en/table.md
  packages/interface/docs/data-display/en/tag.md
  packages/interface/docs/data-display/en/tooltip.md
  packages/interface/docs/data-display/ko/badge.md
  packages/interface/docs/data-display/ko/chip.md
  packages/interface/docs/data-display/ko/divider.md
  packages/interface/docs/data-display/ko/image-avatar.md
  packages/interface/docs/data-display/ko/letter-avatar.md
  packages/interface/docs/data-display/ko/popover.md
  packages/interface/docs/data-display/ko/stats.md
  packages/interface/docs/data-display/ko/table.md
  packages/interface/docs/data-display/ko/tag.md
  packages/interface/docs/data-display/ko/tooltip.md
Labels: Feature
