Repository wrtnlabs/autoview, pull requests merged in 2025-05, with the labels that each got.

#172 Add pagefind search engine
  pnpm-lock.yaml
  website/package.json
Labels: Documentation

#174 feat(compiler): Enhanced TypeScript compiler with detailed configuration.
  assets/compiler-dependencies/package-lock.json
  assets/compiler-dependencies/package.json
  compiler-assets/package.json
  packages/compiler/build/external.js
  packages/compiler/build/raw.js
  packages/compiler/package.json
  packages/compiler/src/AutoViewCompiler.ts
  packages/compiler/src/compilers/TypeScriptCompiler.ts
  packages/interface/src/services/IAutoViewCompilerResult.ts
  pnpm-lock.yaml
  test/tsconfig.json
Labels: Enhancement

#179 feat/chat-agent
  packages/agent/src/agents/AutoViewAgent.ts
  packages/agent/src/agents/AutoViewChatAgent.ts
  packages/agent/src/agents/AutoViewChatAgent/prompt.ts
  packages/agent/src/core/LlmProxy.ts
  packages/agent/src/passes/codegen/Agent.ts
  packages/agent/src/passes/codegen/dto.ts
  packages/agent/src/passes/codegen/prompt.ts
  packages/agent/src/passes/common.ts
  packages/agent/src/structures/agents/IAutoViewChatMessage.ts
  research/src/generate-all-components.ts
  typos.toml
Labels: Feature
